image: continuumio/miniconda3
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
# cache:
#   paths:
#     - .cache/pip
#     - venv/

stages:
- test
- deploy

before_script:
  - conda init bash
  - source ~/.bashrc
  - conda install mamba -c conda-forge
  - mamba create -q -y -n bpp python=3.11
  - conda activate bpp
  - python --version ; pip --version  # For debugging
  - mkdir ~/certs
  - git -c http.sslVerify=false clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.vertices.tech/infrastructure/certificates ~/certs
  - mv ~/certs/root ~/certs/vertices
  - ls -al ~/certs/vertices
test:
  stage: test
  script:
    - pip install tox poetry
    - ls -al ~/certs/vertices
    - poetry config http-basic.vertices gitlab-ci-token $CI_JOB_TOKEN
    - poetry config certificates.vertices.cert ~/certs/vertices/vertices_root_certification_authority.pem
    - poetry config --list
    - tox -p all


sast:
  stage: test
  before_script:
    - ''
include:
- template: Security/SAST.gitlab-ci.yml

# run:
#   script:
#     - pip install .
#     # run the command here
#   artifacts:
#     paths:
#       - build/*

# pages:
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd doc
#     - make html
#     - mv build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+/
  script: 

    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} CURL_CA_BUNDLE="" TWINE_USERNAME=gitlab-ci-token python -m twine upload 
      --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/* 
      --cert ~/certs/vertices/vertices_root_certification_authority.pem
      --verbose

  environment: production

